
services:
  g2o-app:
    build: .
    image: ubicoders/g2o:latest
    container_name: g2o_cnt
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1 
    volumes:
      - "/tmp/.X11-unix/:/tmp/.X11-unix/:rw"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - "/dev/:/dev/"
      # - "./ws_ex:/home/ubuntu/ws_ex:rw"




